


import React, { useState } from 'react';
import Header from './components/Header';
import VirtualTryOn from './components/VirtualTryOn';
import { LookbookGenerator } from './components/LookbookGenerator';
import BackgroundReplacer from './components/BackgroundReplacer';
import PoseChanger from './components/PoseChanger';
import SwapFace from './components/SwapFace';
import { PhotoAlbumCreator } from './components/PhotoAlbumCreator';
import OutfitAnalysis from './components/OutfitAnalysis';
import { Feature, ImageFile } from './types';
import { ImageGalleryProvider } from './contexts/ImageGalleryContext';
import GalleryButton from './components/GalleryButton';
import GalleryModal from './components/modals/GalleryModal';
import { LanguageProvider } from './contexts/LanguageContext';
import { ApiProvider } from './contexts/ApiProviderContext';
import Relight from './components/Relight';
import Upscale from './components/Upscale';
import { ImageEditor } from './components/ImageEditor';
import PoseLibraryModal from './components/modals/PoseLibraryModal';
import { VideoGenerator } from './components/VideoGenerator';
import { SettingsModal } from './components/modals/SettingsModal';
import VideoContinuity from './components/VideoContinuity';
import Inpainting from './components/Inpainting';
import { ImageViewerProvider } from './contexts/ImageViewerContext';
import { GRWMVideoGenerator } from './components/GRWMVideoGenerator';

const AppContent: React.FC = () => {
  const [activeFeature, setActiveFeature] = useState<Feature>(Feature.TryOn);
  const [isGalleryOpen, setIsGalleryOpen] = useState(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState(false);
  const [imageToEdit, setImageToEdit] = useState<ImageFile | null>(null);

  const [isPoseLibraryOpen, setIsPoseLibraryOpen] = useState(false);
  const [poseConfirmCallback, setPoseConfirmCallback] = useState<{ fn: (poses: string[]) => void } | null>(null);
  const [initialSelectedPoses, setInitialSelectedPoses] = useState<string[]>([]);
  
  const handleOpenEditor = (image: ImageFile) => {
    setImageToEdit(image);
    setActiveFeature(Feature.ImageEditor);
    setIsGalleryOpen(false); 
  };
  
  const handleOpenPoseLibrary = (onConfirm: (poses: string[]) => void, initialPoses: string[]) => {
    setPoseConfirmCallback({ fn: onConfirm });
    setInitialSelectedPoses(initialPoses);
    setIsPoseLibraryOpen(true);
  };

  const handlePoseLibraryConfirm = (poses: string[]) => {
    poseConfirmCallback?.fn(poses);
    setIsPoseLibraryOpen(false);
  };

  return (
    <>
      <div className="flex min-h-screen bg-transparent">
        <Header activeFeature={activeFeature} setActiveFeature={setActiveFeature} onOpenSettings={() => setIsSettingsOpen(true)} />
        <div className="flex-1 flex flex-col ml-72"> 
          <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="relative bg-slate-900/70 backdrop-blur-2xl p-6 sm:p-8 rounded-2xl shadow-2xl shadow-black/20 border border-slate-800 min-h-full">
              <div style={{ display: activeFeature === Feature.TryOn ? 'block' : 'none' }}><VirtualTryOn /></div>
              <div style={{ display: activeFeature === Feature.Lookbook ? 'block' : 'none' }}><LookbookGenerator /></div>
              <div style={{ display: activeFeature === Feature.Background ? 'block' : 'none' }}><BackgroundReplacer /></div>
              <div style={{ display: activeFeature === Feature.Pose ? 'block' : 'none' }}><PoseChanger onOpenPoseLibrary={handleOpenPoseLibrary} /></div>
              <div style={{ display: activeFeature === Feature.SwapFace ? 'block' : 'none' }}><SwapFace /></div>
              <div style={{ display: activeFeature === Feature.PhotoAlbum ? 'block' : 'none' }}><PhotoAlbumCreator /></div>
              <div style={{ display: activeFeature === Feature.OutfitAnalysis ? 'block' : 'none' }}><OutfitAnalysis /></div>
              <div style={{ display: activeFeature === Feature.Relight ? 'block' : 'none' }}><Relight /></div>
              <div style={{ display: activeFeature === Feature.Upscale ? 'block' : 'none' }}><Upscale /></div>
              <div style={{ display: activeFeature === Feature.Video ? 'block' : 'none' }}><VideoGenerator /></div>
              <div style={{ display: activeFeature === Feature.VideoContinuity ? 'block' : 'none' }}><VideoContinuity /></div>
              <div style={{ display: activeFeature === Feature.GRWMVideo ? 'block' : 'none' }}><GRWMVideoGenerator /></div>
              <div style={{ display: activeFeature === Feature.Inpainting ? 'block' : 'none' }}><Inpainting /></div>
            </div>
          </main>
          <footer className="text-center py-6 text-slate-500 text-sm flex-shrink-0">
            <p>Powered by Gemini. All images are generated by AI.</p>
          </footer>
        </div>

        <GalleryButton onClick={() => setIsGalleryOpen(true)} />
        {isGalleryOpen && <GalleryModal onClose={() => setIsGalleryOpen(false)} onEditImage={handleOpenEditor} />}
        {isSettingsOpen && <SettingsModal isOpen={isSettingsOpen} onClose={() => setIsSettingsOpen(false)} />}
      </div>

      {isPoseLibraryOpen && (
        <PoseLibraryModal
          isOpen={isPoseLibraryOpen}
          onClose={() => setIsPoseLibraryOpen(false)}
          onConfirm={handlePoseLibraryConfirm}
          initialSelectedPoses={initialSelectedPoses}
        />
      )}

      {activeFeature === Feature.ImageEditor && (
        <ImageEditor
          onClose={() => {
            setActiveFeature(Feature.TryOn);
            setImageToEdit(null);
          }}
          initialImage={imageToEdit}
        />
      )}
    </>
  );
};

const App: React.FC = () => {
  return (
    <LanguageProvider>
      <ApiProvider>
        <ImageGalleryProvider>
          <ImageViewerProvider>
            <AppContent />
          </ImageViewerProvider>
        </ImageGalleryProvider>
      </ApiProvider>
    </LanguageProvider>
  );
};

export default App;